
name: docker build and push tags
on:
  create:
    tags:
      - v*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: docker build and push
      uses: elgohr/Publish-Docker-Github-Action@v5
      with:
        name: chasemoskal/profile-server
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}
        tag_names: true
